# .goreleaser.yaml
project_name: hitime
version: 2

builds:
  # Build configuration for darwin and linux
  - id: linux
    ldflags: &ldflags
      - -s -w -X github.com/gtsteffaniak/hi-time-live/routes.Version={{.Version}}
    main: main.go
    binary: filebrowser
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    hooks:
      post:
        - upx --force-macos {{ .Path }}  # Compress the binary with UPX

  # Build configuration for windows without arm
  - id: windows
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}  # Compress the binary with UPX

  # Build configuration for windows without arm & upx
  - id: windows
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >
      {{- if eq .Os "windows" -}}
      {{.ProjectName}}
      {{- else -}}
      {{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{.ProjectName}}
      {{- end -}}
    format: binary

checksum:
  disable: true

